# Generated by Django 4.0 on 2024-10-17 22:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(choices=[('ARG', 'Argentina'), ('URU', 'Uruguay')], default='ARG', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_currency', models.CharField(choices=[('ARS', 'Argentine Pesos'), ('UYU', 'Uruguayan Pesos')], default='ARS', max_length=3)),
                ('local_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('rejected', 'Rejected')], default='completed', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
